#ifndef GAME_ENTITIES
#define GAME_ENTITIES

#include <stdint.h>
#include "vendor/cglm/cglm.h"

#define MAX_ENTITIES 2000000

// ETNTIY STUFF
int32_t ENTITY_COUNT;
mat4 ENTITY_TRANSFORM[MAX_ENTITIES];
int32_t ENTITY_MODEL[MAX_ENTITIES];
int32_t ENTITY_FACTION[MAX_ENTITIES];
vec3 ENTITY_COLORS[MAX_ENTITIES];
vec3 ENTITY_INERTIA[MAX_ENTITIES];
uint32_t ENTITY_TARGETS[MAX_ENTITIES];
float ENTITY_VEC_THRUST[MAX_ENTITIES];
float ENTITY_THRUST_POWER[MAX_ENTITIES];
vec3 ENTITY_CURRENT_THRUST[MAX_ENTITIES];
float ENTITY_MAX_VEL[MAX_ENTITIES];
vec3 ENTITY_CURRENT_VEC_THRUST[MAX_ENTITIES];
uint32_t PLAYER_CONTROLLED_ENTITY;
vec3 ENTITY_SCALE[MAX_ENTITIES];
float GUN_RELOAD_TIME[MAX_ENTITIES];
float GUN_RELOAD[MAX_ENTITIES];
float GUN_SPEED[MAX_ENTITIES];
bool GUN_ACTIVE[MAX_ENTITIES];
uint32_t GUN_MODEL[MAX_ENTITIES];
uint32_t ENTITY_COLLIDER_GROUP[MAX_ENTITIES];
char *ENTITY_NAME[MAX_ENTITIES];
float ENTITY_DEAD[MAX_ENTITIES];

#endif
