#ifndef GAME_ENTITIES
#define GAME_ENTITIES

#include "vendor/cglm/cglm.h"
#include "vendor/cglm/vec3.h"
#include <stdint.h>

#define MAX_ENTITIES 2000000

// ETNTIY STUFF
int32_t ENTITY_COUNT;
mat4 ENTITY_TRANSFORM[MAX_ENTITIES];
int32_t ENTITY_MODEL[MAX_ENTITIES];
int32_t ENTITY_FACTION[MAX_ENTITIES];
vec3 ENTITY_COLORS[MAX_ENTITIES];
vec3 ENTITY_INERTIA[MAX_ENTITIES];
vec3 ENTITY_LAST_INERTIA[MAX_ENTITIES];
float ENTITY_VEC_THRUST[MAX_ENTITIES];
vec3 ENTITY_THRUST_POWER[MAX_ENTITIES];
vec3 ENTITY_CURRENT_THRUST[MAX_ENTITIES];
vec3 ENTITY_CURRENT_VEC_THRUST[MAX_ENTITIES];
uint32_t PLAYER_CONTROLLED_ENTITY;
vec3 ENTITY_SCALE[MAX_ENTITIES];
float GUN_RELOAD_TIME[MAX_ENTITIES];
float GUN_RELOAD[MAX_ENTITIES];
float GUN_SPEED[MAX_ENTITIES];
bool GUN_ACTIVE[MAX_ENTITIES];
uint32_t GUN_MODEL[MAX_ENTITIES];
uint32_t ENTITY_COLLIDER_GROUP[MAX_ENTITIES];
char *ENTITY_NAME[MAX_ENTITIES];
float ENTITY_DEAD[MAX_ENTITIES];
#define MAX_CONTRACTS_PER_ENTITY 32
uint32_t ENTITY_CONTRACTS[MAX_ENTITIES][MAX_CONTRACTS_PER_ENTITY];
uint32_t ENTITY_ACCEPTED_CONTRACT[MAX_ENTITIES];
uint32_t ENTITY_ONDEATH[MAX_ENTITIES];
int32_t ENTITY_HEALTH[MAX_ENTITIES];
int32_t ENTITY_MAXHEALTH[MAX_ENTITIES];
uint32_t ENTITY_IS_ASTEROID[MAX_ENTITIES];

#define ONDEATH_DELETE 0
#define ONDEATH_EXPLODE 1
#define ONDEATH_SPLIT 2

void entity_set_ondeath(uint32_t entityId, uint32_t trigger) {
  ENTITY_ONDEATH[entityId] = trigger;
}

uint32_t entity_copy(uint32_t src) {
  glm_mat4_copy(ENTITY_TRANSFORM[src], ENTITY_TRANSFORM[ENTITY_COUNT]);
  ENTITY_MODEL[ENTITY_COUNT]   = ENTITY_MODEL[src];
  ENTITY_FACTION[ENTITY_COUNT] = ENTITY_FACTION[src];
  glm_vec3_copy(ENTITY_COLORS[src], ENTITY_COLORS[ENTITY_COUNT]);
  glm_vec3_copy(ENTITY_INERTIA[src], ENTITY_INERTIA[ENTITY_COUNT]);
  ENTITY_VEC_THRUST[ENTITY_COUNT] = ENTITY_VEC_THRUST[src];
  glm_vec3_copy(ENTITY_THRUST_POWER[src], ENTITY_THRUST_POWER[ENTITY_COUNT]);
  glm_vec3_copy(ENTITY_CURRENT_THRUST[src],
                ENTITY_CURRENT_THRUST[ENTITY_COUNT]);
  glm_vec3_copy(ENTITY_CURRENT_VEC_THRUST[src],
                ENTITY_CURRENT_VEC_THRUST[ENTITY_COUNT]);
  glm_vec3_copy(ENTITY_CURRENT_VEC_THRUST[src],
                ENTITY_CURRENT_VEC_THRUST[ENTITY_COUNT]);
  glm_vec3_copy(ENTITY_SCALE[src], ENTITY_SCALE[ENTITY_COUNT]);
  GUN_RELOAD_TIME[ENTITY_COUNT]       = GUN_RELOAD_TIME[src];
  GUN_RELOAD[ENTITY_COUNT]            = GUN_RELOAD[src];
  GUN_SPEED[ENTITY_COUNT]             = GUN_SPEED[src];
  GUN_ACTIVE[ENTITY_COUNT]            = GUN_ACTIVE[src];
  GUN_MODEL[ENTITY_COUNT]             = GUN_MODEL[src];
  ENTITY_COLLIDER_GROUP[ENTITY_COUNT] = ENTITY_COLLIDER_GROUP[src];
  ENTITY_NAME[ENTITY_COUNT]           = ENTITY_NAME[src];
  ENTITY_DEAD[ENTITY_COUNT]           = ENTITY_DEAD[src];
  ENTITY_ONDEATH[ENTITY_COUNT]        = ENTITY_ONDEATH[src];
  ENTITY_HEALTH[ENTITY_COUNT]         = ENTITY_HEALTH[src];
  ENTITY_MAXHEALTH[ENTITY_COUNT]      = ENTITY_MAXHEALTH[src];
  ENTITY_IS_ASTEROID[ENTITY_COUNT]    = ENTITY_IS_ASTEROID[src];

  return ENTITY_COUNT++;
}

void entity_set_health(uint32_t entityId, uint32_t health) {
  ENTITY_HEALTH[entityId]    = health;
  ENTITY_MAXHEALTH[entityId] = health;
}
void entity_set_scale(uint32_t entityId, vec3 scale) {
  glm_vec3_copy(scale, ENTITY_SCALE[entityId]);
}

void entity_set_asteroid(uint32_t entityId, uint32_t is) {
  ENTITY_IS_ASTEROID[entityId] = is;
}

#endif
